// Johnny's Game Library — structured data
// Era: 'childhood' (pre-uni), 'uni' (uni+), 'current'
// goty: year string if it won GOTY (e.g. '2018', 'All-Time'); null/undefined otherwise
// platinum: true if Platinum trophy obtained
// series: shared key so entries from one franchise (and their DLC) sit together
// dlc: true for expansions — clustered right after their base game

const IMG = (typeof window !== "undefined" && window.__IMG_BASE) || "./img";

const RAW_GAMES = [
  // ============ CURRENT ============
  {
    id: "brotato",
    title: "Brotato",
    img: `${IMG}/brotato.png`,
    year: 2022,
    era: "current",
    alsoEra: "uni",
    tag: "roguelite",
    platinum: true,
    goty: "2026",
    company: "blobfish",
    personalNote: "CURRENT OBSESSION.\nCommute fuel.",
  },
  {
    id: "brotato-dlc",
    title: "Brotato: Abyssal Terrors",
    img: `${IMG}/brotato-dlc.png`,
    year: 2024,
    era: "current",
    alsoEra: "uni",
    tag: "roguelite",
    dlc: true,
    baseOf: "brotato",
    company: "blobfish",
  },
  {
    id: "diablo-4",
    title: "Diablo IV",
    img: `${IMG}/diablo-4.jpg`,
    year: 2023,
    era: "uni",
    tag: "arpg",
    series: "diablo",
    company: "blizzard",
  },

  // ============ CHILDHOOD & TEENAGE ============
  {
    id: "aoe2",
    title: "Age of Empires II",
    img: `${IMG}/aoe2.png`,
    year: 1999,
    era: "childhood",
    tag: "strategy",
    personalNote: "LAN parties at the cafe.",
    company: "ensemble",
  },
  {
    id: "aoe2-dlc",
    title: "Age of Empires II: The Conquerors",
    img: `${IMG}/aoe2-dlc.jpg`,
    year: 2000,
    era: "childhood",
    tag: "strategy",
    dlc: true,
    baseOf: "aoe2",
    company: "ensemble",
  },
  {
    id: "red-alert",
    title: "Command & Conquer: Red Alert II",
    img: `${IMG}/red-alert.jpg`,
    year: 2000,
    era: "childhood",
    tag: "strategy",
    series: "cnc",
    company: "westwood",
  },
  {
    id: "diablo-2",
    title: "Diablo II",
    img: `${IMG}/diablo-2.jpg`,
    year: 2000,
    era: "childhood",
    alsoEra: "uni",
    tag: "arpg",
    series: "diablo",
    company: "blizzard",
  },
  {
    id: "diablo-2-dlc",
    title: "Diablo II: Lord of Destruction",
    img: `${IMG}/diablo-2-lod-wide.jpg`,
    year: 2001,
    era: "childhood",
    alsoEra: "uni",
    tag: "arpg",
    series: "diablo",
    dlc: true,
    baseOf: "diablo-2",
    company: "blizzard",
  },
  {
    id: "yuris-revenge",
    title: "Command & Conquer: Yuri's Revenge",
    img: `${IMG}/yuris-revenge.jpg`,
    year: 2001,
    era: "childhood",
    tag: "strategy",
    series: "cnc",
    company: "westwood",
  },
  {
    id: "gta-vc",
    title: "Grand Theft Auto: Vice City",
    img: `${IMG}/gta-vc.png`,
    year: 2002,
    era: "childhood",
    tag: "open-world",
    goty: "All-Time",
    series: "gta",
    alsoEra: "uni",
    company: "rockstar",
    personalNote: "THIS IS WHERE IT ALL BEGAN.",
  },
  {
    id: "warcraft3",
    title: "Warcraft III: Frozen Throne",
    img: `${IMG}/warcraft3.jpg`,
    year: 2003,
    era: "childhood",
    tag: "strategy",
    company: "blizzard",
  },
  {
    id: "cs1-6",
    title: "Counter-Strike 1.6",
    img: `${IMG}/cs1-6.jpg`,
    year: 2003,
    era: "childhood",
    tag: "shooter",
    series: "cs",
    company: "valve",
    personalNote: "de_dust2 is home.",
  },
  {
    id: "dota",
    title: "Dota",
    img: `${IMG}/dota.jpg`,
    year: 2003,
    era: "childhood",
    tag: "moba",
    online: true,
    series: "dota",
    company: "valve",
  },
  {
    id: "gta-sa",
    title: "Grand Theft Auto: San Andreas",
    img: `${IMG}/gta-sa.jpg`,
    year: 2004,
    era: "childhood",
    tag: "open-world",
    series: "gta",
    company: "rockstar",
  },
  {
    id: "fwj",
    title: "Fantasy Westward Journey",
    img: `${IMG}/fantasy-westward-journey.jpg`,
    year: 2004,
    era: "childhood",
    tag: "mmorpg",
    online: true,
    company: "netease",
  },
  {
    id: "dnf",
    title: "Dungeon & Fighter",
    img: `${IMG}/dnf.jpg`,
    year: 2005,
    era: "childhood",
    tag: "beat-em-up",
    online: true,
    company: "neople",
  },
  {
    id: "cf",
    title: "CrossFire",
    img: `${IMG}/cf.jpeg`,
    year: 2007,
    era: "childhood",
    tag: "shooter",
    online: true,
    company: "smilegate",
  },
  {
    id: "cod-mw",
    title: "Call of Duty: Modern Warfare",
    img: `${IMG}/cod-mw.jpg`,
    year: 2007,
    era: "childhood",
    tag: "shooter",
    series: "cod",
    company: "activision",
  },
  {
    id: "devil4",
    title: "Devil May Cry 4",
    img: `${IMG}/devil4.jpg`,
    year: 2008,
    era: "childhood",
    tag: "action",
    series: "dmc",
    company: "capcom",
  },
  {
    id: "cod-waw",
    title: "Call of Duty: World at War",
    img: `${IMG}/cod-waw.png`,
    year: 2008,
    era: "childhood",
    tag: "shooter",
    series: "cod",
    company: "activision",
  },
  {
    id: "cod-mw2",
    title: "Call of Duty: Modern Warfare II",
    img: `${IMG}/cod-mw2.jpg`,
    year: 2009,
    era: "childhood",
    tag: "shooter",
    series: "cod",
    company: "activision",
  },
  {
    id: "pvz",
    title: "Plants vs Zombies",
    img: `${IMG}/pvz.jpg`,
    year: 2009,
    era: "childhood",
    tag: "tower-defense",
    company: "popcap",
  },
  {
    id: "lol",
    title: "League of Legends",
    img: `${IMG}/lol.jpg`,
    year: 2009,
    era: "childhood",
    tag: "moba",
    online: true,
    company: "riot",
  },
  {
    id: "prototype",
    title: "Prototype",
    img: `${IMG}/prototype.jpg`,
    year: 2009,
    era: "childhood",
    tag: "action",
    company: "radical",
  },
  {
    id: "minecraft",
    title: "Minecraft",
    img: `${IMG}/minecraft.jpg`,
    year: 2009,
    era: "childhood",
    tag: "sandbox",
    company: "mojang",
  },
  {
    id: "cod-blackops",
    title: "Call of Duty: Black Ops",
    img: `${IMG}/cod-blackops.jpg`,
    year: 2010,
    era: "childhood",
    tag: "shooter",
    series: "cod",
    company: "activision",
  },
  {
    id: "cod-mw3",
    title: "Call of Duty: Modern Warfare III",
    img: `${IMG}/cod-mw3.jpg`,
    year: 2011,
    era: "childhood",
    tag: "shooter",
    series: "cod",
    company: "activision",
  },
  {
    id: "kof",
    title: "The King of Fighters",
    img: `${IMG}/kof.jpg`,
    year: 1994,
    era: "childhood",
    tag: "fighting",
    company: "snk",
  },
  {
    id: "street-fighter",
    title: "Street Fighter",
    img: `${IMG}/street-fighter.jpg`,
    year: 1987,
    era: "childhood",
    tag: "fighting",
    company: "capcom",
  },
  {
    id: "metal-slug",
    title: "Metal Slug",
    img: `${IMG}/metal-slug.jpeg`,
    year: 1996,
    era: "childhood",
    tag: "arcade",
    company: "snk",
  },
  {
    id: "contra",
    title: "Contra",
    img: `${IMG}/contra.jpg`,
    year: 1987,
    era: "childhood",
    tag: "arcade",
    company: "konami",
  },
  {
    id: "road-rash",
    title: "Road Rash",
    img: `${IMG}/road-rash.jpg`,
    year: 1991,
    era: "childhood",
    tag: "racing",
    company: "ea",
  },
  {
    id: "nba2k",
    title: "NBA 2K Series",
    img: `${IMG}/nba2k.png`,
    year: 1999,
    era: "childhood",
    tag: "sports",
    series: "nba2k",
    company: "2k",
  },

  // ============ UNIVERSITY+ ============
  {
    id: "gta-3",
    title: "GTA III",
    img: `${IMG}/gta-3.jpg`,
    year: 2001,
    era: "uni",
    tag: "open-world",
    series: "gta",
    company: "rockstar",
  },
  {
    id: "gta-4",
    title: "Grand Theft Auto IV",
    img: `${IMG}/gta-4.jpg`,
    year: 2008,
    era: "uni",
    tag: "open-world",
    series: "gta",
    company: "rockstar",
  },
  {
    id: "gta-4-dlc",
    title: "GTA IV: Episodes from Liberty City",
    img: `${IMG}/gta-4-dlc-full.jpg`,
    parts: ["The Lost and Damned", "The Ballad of Gay Tony"],
    year: 2009,
    era: "uni",
    tag: "open-world",
    series: "gta",
    dlc: true,
    baseOf: "gta-4",
    company: "rockstar",
  },
  {
    id: "limbo",
    title: "Limbo",
    img: `${IMG}/limbo.jpeg`,
    year: 2010,
    era: "uni",
    tag: "puzzle",
    company: "playdead",
  },
  {
    id: "dark-souls-1",
    title: "Dark Souls",
    img: `${IMG}/dark-souls-1.jpg`,
    year: 2011,
    era: "uni",
    tag: "soulslike",
    platinum: true,
    goty: "2018",
    series: "dark-souls",
    company: "fromsoftware",
    personalNote: "Long may the sun shine!",
  },
  {
    id: "dark-souls-1-dlc",
    title: "Dark Souls: Artorias of the Abyss",
    img: `${IMG}/dark-souls-1-dlc.jpg`,
    year: 2012,
    era: "uni",
    tag: "soulslike",
    series: "dark-souls",
    dlc: true,
    baseOf: "dark-souls-1",
    company: "fromsoftware",
  },
  {
    id: "gta-5",
    title: "Grand Theft Auto V",
    img: `${IMG}/gta-5.png`,
    year: 2013,
    era: "uni",
    tag: "open-world",
    goty: "2018",
    series: "gta",
    company: "rockstar",
  },
  {
    id: "dota-2",
    title: "Dota 2",
    img: `${IMG}/dota-2.jpeg`,
    year: 2013,
    era: "uni",
    tag: "moba",
    online: true,
    series: "dota",
    company: "valve",
  },
  {
    id: "hearthstone",
    title: "Hearthstone",
    img: `${IMG}/hearthstone.jpg`,
    year: 2014,
    era: "uni",
    tag: "card",
    online: true,
    company: "blizzard",
  },
  {
    id: "dark-souls-2",
    title: "Dark Souls II",
    img: `${IMG}/dark-souls-2-dlc.jpg`,
    year: 2014,
    era: "uni",
    tag: "soulslike",
    series: "dark-souls",
    company: "fromsoftware",
  },
  {
    id: "dark-souls-2-dlc-crowns",
    title: "Dark Souls II: The Lost Crowns",
    img: `${IMG}/dark-souls-2-crowns.png`,
    year: 2014,
    era: "uni",
    tag: "soulslike",
    series: "dark-souls",
    dlc: true,
    baseOf: "dark-souls-2",
    company: "fromsoftware",
  },
  {
    id: "goat",
    title: "Goat Simulator",
    img: `${IMG}/goat.jpg`,
    year: 2014,
    era: "uni",
    tag: "sandbox",
    company: "coffee-stain",
  },
  {
    id: "bloodborne",
    title: "Bloodborne",
    img: `${IMG}/bloodborne.jpg`,
    year: 2015,
    era: "uni",
    tag: "soulslike",
    goty: "2022",
    series: "bloodborne",
    company: "fromsoftware",
    personalNote: "May you find your worth\nin the waking world.",
  },
  {
    id: "bloodborne-dlc",
    title: "Bloodborne: The Old Hunters",
    img: `${IMG}/bloodborne-dlc.jpg`,
    year: 2015,
    era: "uni",
    tag: "soulslike",
    series: "bloodborne",
    dlc: true,
    baseOf: "bloodborne",
    company: "fromsoftware",
  },
  {
    id: "witcher3",
    title: "The Witcher 3: Wild Hunt",
    img: `${IMG}/witcher3.jpg`,
    year: 2015,
    era: "uni",
    tag: "rpg",
    company: "cdpr",
  },
  {
    id: "titan-fall-2",
    title: "Titanfall 2",
    img: `${IMG}/titan-fall-2.jpeg`,
    year: 2016,
    era: "uni",
    tag: "shooter",
    company: "respawn",
  },
  {
    id: "inside",
    title: "Inside",
    img: `${IMG}/inside.jpg`,
    year: 2016,
    era: "uni",
    tag: "puzzle",
    goty: "2021",
    company: "playdead",
  },
  {
    id: "overcooked",
    title: "Overcooked!",
    img: `${IMG}/overcooked.jpg`,
    year: 2016,
    era: "uni",
    tag: "co-op",
    series: "overcooked",
    company: "team17",
  },
  {
    id: "dark-souls-3",
    title: "Dark Souls III",
    img: `${IMG}/dark-souls-3.jpg`,
    year: 2016,
    era: "uni",
    tag: "soulslike",
    platinum: true,
    goty: "2020",
    series: "dark-souls",
    company: "fromsoftware",
    personalNote: "Ashen one, hearest thou\nmy voice, still?",
  },
  {
    id: "dark-souls-3-dlc",
    title: "Dark Souls III: DLCs",
    img: `${IMG}/dark-souls-3-dlcs.png`,
    year: 2017,
    era: "uni",
    tag: "soulslike",
    series: "dark-souls",
    dlc: true,
    baseOf: "dark-souls-3",
    company: "fromsoftware",
  },
  {
    id: "storm",
    title: "Naruto: Ultimate Ninja Storm 4",
    img: `${IMG}/storm.jpg`,
    year: 2016,
    era: "uni",
    tag: "fighting",
    company: "bandai",
  },
  {
    id: "zelda-breath",
    title: "The Legend of Zelda: Breath of the Wild",
    img: `${IMG}/zelda-breath.jpg`,
    year: 2017,
    era: "uni",
    tag: "open-world",
    goty: "2023",
    series: "zelda",
    company: "nintendo",
  },
  {
    id: "nioh",
    title: "Nioh",
    img: `${IMG}/nioh.jpg`,
    year: 2017,
    era: "uni",
    tag: "soulslike",
    series: "nioh",
    company: "team-ninja",
  },
  {
    id: "nioh-dlc",
    title: "Nioh: DLCs",
    img: `${IMG}/nioh-dlc-filled.jpg`,
    parts: ["Dragon of the North", "Defiant Honor", "Bloodshed\u2019s End"],
    year: 2017,
    era: "uni",
    tag: "soulslike",
    series: "nioh",
    dlc: true,
    baseOf: "nioh",
    company: "team-ninja",
    parts: ["Dragon of the North", "Defiant Honor", "Bloodshed's End"],
  },
  {
    id: "pubg",
    title: "PUBG: Battlegrounds",
    img: `${IMG}/pubg.jpeg`,
    year: 2017,
    era: "uni",
    tag: "battle-royale",
    online: true,
    company: "krafton",
  },
  {
    id: "overcooked2",
    title: "Overcooked! 2",
    img: `${IMG}/overcooked2.jpeg`,
    year: 2018,
    era: "uni",
    tag: "co-op",
    series: "overcooked",
    company: "team17",
  },
  {
    id: "a-way-out",
    title: "A Way Out",
    img: `${IMG}/a-way-out.jpg`,
    year: 2018,
    era: "uni",
    tag: "co-op",
    company: "hazelight",
  },
  {
    id: "rdr2",
    title: "Red Dead Redemption 2",
    img: `${IMG}/rdr2.jpg`,
    year: 2018,
    era: "uni",
    tag: "open-world",
    company: "rockstar",
  },
  {
    id: "unravel2",
    title: "Unravel Two",
    img: `${IMG}/unravel2.jpeg`,
    year: 2018,
    era: "uni",
    tag: "co-op",
    company: "coldwood",
  },
  {
    id: "sekiro",
    title: "Sekiro: Shadows Die Twice",
    img: `${IMG}/sekiro.jpg`,
    year: 2019,
    era: "uni",
    tag: "soulslike",
    platinum: true,
    goty: "2019",
    company: "fromsoftware",
    personalNote: "Hesitation is defeat.",
  },
  {
    id: "death-stranding",
    title: "Death Stranding",
    img: `${IMG}/death-stranding.jpg`,
    year: 2019,
    era: "uni",
    tag: "open-world",
    goty: "2024",
    company: "kojima",
  },
  {
    id: "slay-the-spire",
    title: "Slay the Spire",
    img: `${IMG}/slay-the-spire.jpeg`,
    year: 2019,
    era: "uni",
    tag: "roguelite",
    company: "megacrit",
  },
  {
    id: "nfs-heat",
    title: "Need For Speed: Heat",
    img: `${IMG}/nfs-heat.jpg`,
    year: 2019,
    era: "uni",
    tag: "racing",
    company: "ea",
  },
  {
    id: "dmc5",
    title: "Devil May Cry 5",
    img: `${IMG}/dmc5.jpg`,
    year: 2019,
    era: "uni",
    tag: "action",
    series: "dmc",
    company: "capcom",
  },
  {
    id: "ori-will",
    title: "Ori and the Will of the Wisps",
    img: `${IMG}/ori-will.jpg`,
    year: 2020,
    era: "uni",
    tag: "metroidvania",
    company: "moon",
  },
  {
    id: "hades",
    title: "Hades",
    img: `${IMG}/hades.png`,
    year: 2020,
    era: "uni",
    tag: "roguelite",
    goty: "2020",
    company: "supergiant",
    personalNote: "One more run... one more.",
  },
  {
    id: "cyberpunk",
    title: "Cyberpunk 2077",
    img: `${IMG}/cyberpunk.png`,
    year: 2020,
    era: "uni",
    tag: "open-world",
    platinum: true,
    goty: "2021",
    series: "cyberpunk",
    company: "cdpr",
  },
  {
    id: "cyberpunk-dlc",
    title: "Cyberpunk 2077: Phantom Liberty",
    img: `${IMG}/cyberpunk-dlc.jpg`,
    year: 2023,
    era: "uni",
    tag: "open-world",
    series: "cyberpunk",
    dlc: true,
    baseOf: "cyberpunk",
    company: "cdpr",
  },
  {
    id: "nba2k21",
    title: "NBA 2K21",
    img: `${IMG}/nba2k21.jpg`,
    year: 2020,
    era: "uni",
    tag: "sports",
    series: "nba2k",
    company: "2k",
  },
  {
    id: "nioh2",
    title: "Nioh 2",
    img: `${IMG}/nioh2.jpg`,
    year: 2020,
    era: "uni",
    tag: "soulslike",
    series: "nioh",
    company: "team-ninja",
  },
  {
    id: "goose",
    title: "Goose Goose Duck",
    img: `${IMG}/goose.jpeg`,
    year: 2021,
    era: "uni",
    tag: "social",
    online: true,
    company: "gaggle",
  },
  {
    id: "fist",
    title: "F.I.S.T. Forged In Shadow Torch",
    img: `${IMG}/fist.jpg`,
    year: 2021,
    era: "uni",
    tag: "metroidvania",
    goty: "2023",
    company: "tigame",
  },
  {
    id: "it-takes-two",
    title: "It Takes Two",
    img: `${IMG}/it-takes-two.jpg`,
    year: 2021,
    era: "uni",
    tag: "co-op",
    platinum: true,
    goty: "2023",
    company: "hazelight",
    personalNote: "Co-op nights. Every level.",
  },
  {
    id: "elden-ring",
    title: "Elden Ring",
    img: `${IMG}/elden-ring.jpg`,
    year: 2022,
    era: "uni",
    tag: "soulslike",
    goty: "2022",
    platinum: true,
    series: "elden-ring",
    company: "fromsoftware",
  },
  {
    id: "elden-ring-dlc",
    title: "Elden Ring: Shadow of the Erdtree",
    img: `${IMG}/elden-ring-dlc.jpg`,
    year: 2024,
    era: "uni",
    tag: "soulslike",
    series: "elden-ring",
    dlc: true,
    baseOf: "elden-ring",
    company: "fromsoftware",
  },
  {
    id: "sifu",
    title: "Sifu",
    img: `${IMG}/sifu.jpeg`,
    year: 2022,
    era: "uni",
    tag: "action",
    company: "sloclap",
  },
  {
    id: "cs-2",
    title: "Counter-Strike 2",
    img: `${IMG}/cs-2.jpeg`,
    year: 2023,
    era: "uni",
    tag: "shooter",
    online: true,
    series: "cs",
    company: "valve",
  },
  {
    id: "zelda-tears",
    title: "The Legend of Zelda: Tears of the Kingdom",
    img: `${IMG}/zelda-tears.jpg`,
    year: 2023,
    era: "uni",
    tag: "open-world",
    series: "zelda",
    company: "nintendo",
  },
  {
    id: "zelda-echo",
    title: "The Legend of Zelda: Echoes of Wisdom",
    img: `${IMG}/zelda-echo.jpg`,
    year: 2024,
    era: "uni",
    tag: "adventure",
    series: "zelda",
    company: "nintendo",
  },
  {
    id: "balatro",
    title: "Balatro",
    img: `${IMG}/balatro.jpg`,
    year: 2024,
    era: "uni",
    tag: "card",
    company: "localthunk",
  },
  {
    id: "wukong",
    title: "Black Myth: Wukong",
    img: `${IMG}/wukong.jpg`,
    year: 2024,
    era: "uni",
    tag: "action",
    platinum: true,
    goty: "2024",
    company: "game-science",
    personalNote: "Souls combat, my heritage.",
  },
  {
    id: "split-fiction",
    title: "Split Fiction",
    img: `${IMG}/split-fiction.jpg`,
    year: 2025,
    era: "uni",
    tag: "co-op",
    goty: "2025",
    company: "hazelight",
  },
  {
    id: "dead-cells",
    title: "Dead Cells",
    img: `${IMG}/dead-cells.jpg`,
    year: 2018,
    era: "uni",
    tag: "roguelite",
    goty: "2025",
    company: "motion-twin",
  },
  {
    id: "dead-cells-dlc",
    title: "Dead Cells: DLCs",
    img: `${IMG}/dead-cells-dlcs.png`,
    parts: [
      "Rise of the Giant",
      "The Bad Seed",
      "Fatal Falls",
      "The Queen and the Sea",
      "Return to Castlevania",
    ],
    year: 2023,
    era: "uni",
    tag: "roguelite",
    dlc: true,
    baseOf: "dead-cells",
    company: "motion-twin",
  },
];

// Cluster by studio first, then by franchise (with its DLC), then chronologically —
// each group stays where its first entry already sat.
function clusterBy(list, keyOf) {
  const order = [],
    buckets = new Map();
  list.forEach((g) => {
    const key = keyOf(g);
    if (!buckets.has(key)) {
      buckets.set(key, []);
      order.push(key);
    }
    buckets.get(key).push(g);
  });
  return order.map((key) => buckets.get(key));
}

function clusterLibrary(list) {
  return clusterBy(list, (g) => g.company || g.series || g.id).flatMap((byCompany) =>
    clusterBy(byCompany, (g) => g.series || g.id).flatMap((bySeries) =>
      bySeries
        .slice()
        .sort((a, b) => a.year - b.year || (a.dlc ? 1 : 0) - (b.dlc ? 1 : 0)),
    ),
  );
}

const GAMES = clusterLibrary(RAW_GAMES);

const GAMES_BY_ID = Object.fromEntries(GAMES.map((g) => [g.id, g]));

const GOTYS = [
  { year: "All-Time", games: ["gta-vc"] },
  { year: "2018", games: ["gta-5", "dark-souls-1"] },
  { year: "2019", games: ["sekiro"] },
  { year: "2020", games: ["dark-souls-3", "hades"] },
  { year: "2021", games: ["inside", "cyberpunk"] },
  { year: "2022", games: ["bloodborne", "elden-ring"] },
  { year: "2023", games: ["it-takes-two", "zelda-breath", "fist"] },
  { year: "2024", games: ["wukong", "death-stranding"] },
  { year: "2025", games: ["split-fiction", "dead-cells"] },
  { year: "2026", games: ["brotato"] },
];

// ---------------------------------------------------------------------------
// SECTION ORDER — hand-curated in game-list.txt, mirrored here verbatim.
// Each section is an explicit ordered list of ids. `null` = a group break
// (renders as a row break / divider, keeping franchise clusters together).
// A game may appear in several sections; duplicates are intentional.
// ---------------------------------------------------------------------------
const SECTIONS = {
  uni: [
    "wukong",
    null,
    "diablo-2",
    "diablo-2-dlc",
    null,
    "gta-vc",
    "gta-3",
    "gta-4",
    "gta-4-dlc",
    "gta-5",
    null,
    "fist",
    null,
    "dark-souls-1",
    "dark-souls-1-dlc",
    "dark-souls-2",
    "dark-souls-2-dlc-crowns",
    "dark-souls-3",
    "dark-souls-3-dlc",
    null,
    "bloodborne",
    "bloodborne-dlc",
    null,
    "sekiro",
    null,
    "elden-ring",
    "elden-ring-dlc",
    null,
    "inside",
    null,
    "cyberpunk",
    "cyberpunk-dlc",
    null,
    "a-way-out",
    "it-takes-two",
    "split-fiction",
    null,
    "titan-fall-2",
    null,
    "zelda-breath",
    "zelda-tears",
    "zelda-echo",
    null,
    "overcooked",
    "overcooked2",
    null,
    "nioh",
    "nioh-dlc",
    null,
    "brotato",
    "brotato-dlc",
    "hades",
    "dead-cells",
    "dead-cells-dlc",
    null,
    "slay-the-spire",
    null,
    "ori-will",
    null,
    "nfs-heat",
    "balatro",
    "storm",
    "nba2k21",
  ],
  childhood: [
    "gta-vc",
    "gta-sa",
    "diablo-2",
    "diablo-2-dlc",
    null,
    "aoe2",
    "aoe2-dlc",
    "red-alert",
    "yuris-revenge",
    null,
    "cs1-6",
    "warcraft3",
    "pvz",
    null,
    "contra",
    "metal-slug",
    "road-rash",
    "street-fighter",
    "kof",
    null,
    "prototype",
    "devil4",
    null,
    "nba2k",
    "minecraft",
    null,
    "cod-mw",
    "cod-waw",
    "cod-mw2",
    "cod-blackops",
    "cod-mw3",
  ],
  online: [
    "fwj",
    "cf",
    "dnf",
    "dota",
    "dota-2",
    "lol",
    "pubg",
    "hearthstone",
    "goose",
    "cs-2",
  ],
  unfinished: [
    "death-stranding",
    null,
    "rdr2",
    null,
    "nioh2",
    null,
    "witcher3",
    null,
    "sifu",
    "dmc5",
    "diablo-4",
    "limbo",
    "unravel2",
    "goat",
  ],
};

// Why each shelved game stopped. status: 'paused' (may resume) | 'dropped' (done with it).
// DRAFT COPY — edit freely; any missing field just doesn't render.
const UNFINISHED_NOTES = {
  "death-stranding": {
    status: "paused",
    reason: "Cargo runs turned into a commute; life got loud.",
    verdict: "Will resume",
  },
  rdr2: {
    status: "paused",
    reason: "Every session wants an hour before anything happens.",
    verdict: "Will resume",
  },
  nioh2: {
    status: "paused",
    reason: "Difficulty wall, and Sekiro already scratched that itch.",
    verdict: "Maybe",
  },
  witcher3: {
    status: "paused",
    reason: "Drowned in question marks, never found the story again.",
    verdict: "Maybe",
  },
  sifu: {
    status: "paused",
    reason: "Kept aging out on the same stage. Rage-shelved it.",
    verdict: "Maybe",
  },
  dmc5: {
    status: "paused",
    reason: "Combo ceiling too high for how little I played.",
    verdict: "Maybe",
  },
  "diablo-4": {
    status: "dropped",
    reason: "Endgame loop felt like homework, not loot.",
    verdict: "Not coming back",
  },
  limbo: {
    status: "dropped",
    reason: "Bought it late, played it in the wrong mood.",
    verdict: "Not coming back",
  },
  unravel2: {
    status: "dropped",
    reason: "Co-op only, and my player two moved away.",
    verdict: "Done with it",
  },
  goat: {
    status: "dropped",
    reason: "The joke landed, then there was nothing left.",
    verdict: "Done with it",
  },
};

const UNFINISHED = SECTIONS.unfinished
  .filter(Boolean)
  .map((id) => ({ id, ...(UNFINISHED_NOTES[id] || {}) }));

// Resolve a section's id list to game objects, keeping order and group breaks.
function sectionGames(key) {
  return (SECTIONS[key] || []).map((id) =>
    id === null ? null : GAMES_BY_ID[id] || null,
  );
}

const STATS = {
  total: GAMES.length,
  childhood: SECTIONS.childhood.filter(Boolean).length,
  uni: SECTIONS.uni.filter(Boolean).length,
  online: SECTIONS.online.filter(Boolean).length,
  goty: GOTYS.reduce((a, y) => a + y.games.length, 0),
  unfinished: UNFINISHED.length,
  earliest: Math.min(...GAMES.map((g) => g.year)),
  latest: Math.max(...GAMES.map((g) => g.year)),
};

window.GAMES = GAMES;
window.GAMES_BY_ID = GAMES_BY_ID;
window.GOTYS = GOTYS;
window.STATS = STATS;
window.UNFINISHED = UNFINISHED;
window.SECTIONS = SECTIONS;
window.sectionGames = sectionGames;
